apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoic2VyZ2V5YmUxYW4iLCJwYXNzd29yZCI6ImdpdGh1Yl9wYXRfMTFBRTdaNFNJMG45eG8zUnZrcmJ1c19YeGN0U3licjVjMTQ4WXMzWmlsc2ZFdGoyMlZNUWI3SGF3eHlOUmw2YW9JQlQyWFNVVjJocUdVRVp4MiIsImF1dGgiOiJjMlZ5WjJWNVltVXhZVzQ2WjJsMGFIVmlYM0JoZEY4eE1VRkZOMW8wVTBrd2JqbDRiek5TZG10eVluVnpYMWg0WTNSVGVXSnlOV014TkRoWmN6TmFhV3h6WmtWMGFqSXlWazFSWWpkSVlYZDRlVTVTYkRaaGIwbENWREpZVTFWV01taHhSMVZGV25neSJ9fX0=
type: kubernetes.io/dockerconfigjson